name: Discord Message
on:
  push:
    branches: [main, uat, dev]
  pull_request:
    branches: [main, uat, dev]

jobs:
  discord-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification for Push
        if: github.event_name == 'push'
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "GitHub"
          message: "🎉 New update on #${{ github.ref_name }} by ${{ github.event.head_commit.author.name }} ♪♫*•♪(*´∀｀)♪♫*•♪ !\n\n**${{ github.event.head_commit.message }}**\n\nView Changes: ${{ github.event.head_commit.url }}"

      - name: Send Discord Notification for Pull Request
        if: github.event_name == 'pull_request'
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#4285f4"
          username: "GitHub"
          message: "🎉 New update on #${{ github.ref_name }} by ${{ github.event.head_commit.author.name }} ♪♫*•♪(*´∀｀)♪♫*•♪ !\n\n**$${{ github.event.pull_request.title }}**\n${{ github.event.pull_request.body }}.\n\nView Changes: ${{ github.event.head_commit.url }}"